name: Backend CI/CD Pipeline

on:
  # Triggeren bij push naar main branch, maar alleen als er wijzigingen zijn in backend code
  push:
    branches: [ main ]
    paths:
      - 'src/backend/**'
      - '.github/workflows/backend-pipeline.yml'
  
  # Triggeren bij PR naar main branch, maar alleen als er wijzigingen zijn in backend code
  pull_request:
    branches: [ main ]
    paths:
      - 'src/backend/**'
  
  # Handmatige trigger
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - test
          - production

# Rechten die de workflow nodig heeft
permissions:
  contents: read
  checks: write
  pull-requests: write
  id-token: write  # Nodig voor OIDC authenticatie met Azure

# Variabelen die in de hele workflow gebruikt kunnen worden
env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_PATH: 'Manuals.sln'
  API_PROJECT_PATH: 'src/backend/Manuals.API/Manuals.API.csproj'
  TEST_PATH: 'tests/backend/'

jobs:
  build-and-deploy:
    name: Build, Test and Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'development' }}
    
    steps:
    # Repository uitchecken
    - name: Checkout repository
      uses: actions/checkout@v3
    
    # .NET setup
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    # NuGet packages herstellen
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
    
    # Solution bouwen
    - name: Build solution
      run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore
    
    # Tests uitvoeren
    - name: Run tests
      run: dotnet test ${{ env.TEST_PATH }} --configuration Release --no-build --verbosity normal
    
    # Build artifact publiceren
    - name: Publish API project
      if: success() && (github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch')
      run: dotnet publish ${{ env.API_PROJECT_PATH }} -c Release -o publish
    
    # Bepaal welke app name we gebruiken op basis van environment
    - name: Set environment variables
      id: env_vars
      if: success() && (github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch')
      run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          ENV="${{ inputs.environment }}"
        else
          ENV="development"
        fi
        
        # App naam op basis van environment
        if [ "$ENV" == "development" ]; then
          APP_NAME="app-manuals-api-dev"
        elif [ "$ENV" == "test" ]; then
          APP_NAME="app-manuals-api-test"
        elif [ "$ENV" == "production" ]; then
          APP_NAME="app-manuals-api-prod"
        fi
        
        echo "environment=$ENV" >> $GITHUB_OUTPUT
        echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT
    
    # Azure login met dezelfde OIDC methode als infrastructure workflow
    - name: Azure login
      if: success() && (github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch')
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    # Deploy naar Azure Web App
    - name: Deploy to Azure Web App
      if: success() && (github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch')
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ steps.env_vars.outputs.app_name }}
        package: publish
    
    # Post-deployment status melding
    - name: Post deployment success message
      if: success() && (github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch')
      run: |
        echo "Backend successfully deployed to ${{ steps.env_vars.outputs.app_name }} (${{ steps.env_vars.outputs.environment }})"
